POST http://localhost:8080/profile/skill
Content-Type: application/json

{
  "user": "63dddee66d67ea2e63f428f1",
  "content": "Hosting"
}

###

POST http://localhost:8080/profile/award
Content-Type: application/json

{
  "user": "63dddee66d67ea2e63f428f1",
  "content": "Spokesperson for Kokoa-Koloa"
}

###

POST http://localhost:8080/profile/post
Content-Type: application/json

{
  "user": "63dddee66d67ea2e63f428f1",
  "content": "I truly believe that I am the Bill Burr of the improv stage."
}

###

POST http://localhost:8080/profile/experience
Content-Type: application/json

{
  "user": "63dddee66d67ea2e63f428f1",
  "title": "Host",
  "venue": "Park Tavern",
  "content": "Host comedy show weekly"
}

###

PUT http://localhost:8080/profile/skill/63dddf3f6d67ea2e63f428fc
Content-Type: application/json

###

PUT http://localhost:8080/profile/award/63dddf5b6d67ea2e63f428ff
Content-Type: application/json

{
  "content": "Spokesperson for Hungry jakes"
}

###

PUT http://localhost:8080/profile/post/63dddf806d67ea2e63f42904
Content-Type: application/json

{
  "content": "I am not man but"
}

###

PUT http://localhost:8080/profile/post/likes/63dddf806d67ea2e63f42904

###

PUT http://localhost:8080/profile/about/63dddee66d67ea2e63f428f1
Content-Type: application/json

{
  "content": "I just received the initial deposit for a corporate show in Dubai that's coming up in a couple of weeks. The show pays $8000, yes, that's right, EIGHT THOUSAND US DOLLARS for less than one hour's work! And yes, I'll be flying in First Class as usual, in unbelievable luxury, with a flat bed! I'll be checking out the indoor ski range, surfing on the sand dunes, visiting the tallest building in the world and the world's largest shopping mall, and luxuriating by the pool at my five star hotel. And yes, I will send pictures!"
}
###

PUT http://localhost:8080/profile/experience/63dddfb16d67ea2e63f42907
Content-Type: application/json

{
  "title": "Host",
  "venue": "Park Tavern",
  "content": "Host comedy show monthly",
}

###
PUT http://localhost:8080/profile/hero/63dddee66d67ea2e63f428f1
Content-Type: application/json

{
  "firstName": "George",
  "lastName": "Castles",
  "tagline": "The show didn't get canceled, I quit.",
  "city": "Bangkok",
  "country": "Thailand",
  "socials": ["@GeorgeCastles1", "@GeorgeCastles1", "@GeorgeCastles1"]

}

###

GET http://localhost:8080/profile/63dddee66d67ea2e63f428f1
Content-Type: application/json

###

DELETE http://localhost:8080/profile/skill/63dddf3f6d67ea2e63f428fc
Content-Type: application/json

###

DELETE http://localhost:8080/profile/award/63dddf5b6d67ea2e63f428ff
Content-Type: application/json

###

DELETE http://localhost:8080/profile/post/63dddf806d67ea2e63f42904
Content-Type: application/json

###

DELETE http://localhost:8080/profile/experience/63dddfb16d67ea2e63f42907
Content-Type: application/json
